set(HELP_LAUNCHER_TARGET "${PROJECT_NAME}-help")
set(HELP_LAUNCHER_TARGET "${HELP_LAUNCHER_TARGET}" PARENT_SCOPE)
add_executable(${HELP_LAUNCHER_TARGET} "${CMAKE_CURRENT_SOURCE_DIR}/main.c")
set_target_properties(${HELP_LAUNCHER_TARGET} PROPERTIES BUILD_RPATH "${APP_RPATH}")
set_target_properties(${HELP_LAUNCHER_TARGET} PROPERTIES OUTPUT_NAME "${EXE_NAME}-help")
target_compile_definitions(${HELP_LAUNCHER_TARGET} PRIVATE -D_CRT_SECURE_NO_WARNINGS)
