execute_process(
    COMMAND git rev-parse HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT
    RESULT_VARIABLE GIT_RESULT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT_SHORT
    RESULT_VARIABLE GIT_RESULT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

add_library(${BUILD_METADATA_LIB} STATIC "${BUILD_METADATA_FILE}")
add_custom_command(
	TARGET ${BUILD_METADATA_LIB} PRE_BUILD
	COMMAND "${CMAKE_COMMAND}" -E touch "${BUILD_METADATA_FILE}"
	VERBATIM
)
add_custom_target(GenerateBuildMetadata DEPENDS "${CMAKE_SOURCE_DIR}/${BUILD_METADATA_FILE}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE CMAKE_SYSTEM="${CMAKE_SYSTEM}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE CMAKE_SYSTEM_NAME="${CMAKE_SYSTEM_NAME}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE CMAKE_VERSION="${CMAKE_VERSION}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE C_COMPILER="${CMAKE_C_COMPILER_ID}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE C_COMPILER_VERSION="${CMAKE_C_COMPILER_VERSION}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE CXX_COMPILER="${CMAKE_CXX_COMPILER_ID}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE CXX_COMPILER_VERSION="${CMAKE_CXX_COMPILER_VERSION}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE C_LINKER="${CMAKE_C_COMPILER_LINKER_ID}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE C_LINKER_VERSION="${CMAKE_C_COMPILER_LINKER_VERSION}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE CXX_LINKER="${CMAKE_CXX_COMPILER_LINKER_ID}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE CXX_LINKER_VERSION="${CMAKE_CXX_COMPILER_LINKER_VERSION}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE GIT_COMMIT="${GIT_COMMIT}")
target_compile_definitions(${BUILD_METADATA_LIB} PRIVATE GIT_COMMIT_SHORT="${GIT_COMMIT_SHORT}")
