execute_process(
	COMMAND git rev-parse HEAD
	WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
	OUTPUT_VARIABLE GIT_COMMIT
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
	COMMAND git rev-parse --short HEAD
	WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
	OUTPUT_VARIABLE GIT_COMMIT_SHORT
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
	COMMAND git rev-parse HEAD
	WORKING_DIRECTORY ${raylib_SOURCE_DIR}
	OUTPUT_VARIABLE RAYLIB_COMMIT
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
	COMMAND git rev-parse --short HEAD
	WORKING_DIRECTORY ${raylib_SOURCE_DIR}
	OUTPUT_VARIABLE RAYLIB_COMMIT_SHORT
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(BUILD_METADATA_FILE "${CMAKE_BINARY_DIR}/src/build-metadata.cpp")
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/build-metadata.cpp.in"
	"${BUILD_METADATA_FILE}")
add_library(${BUILD_METADATA_TARGET} STATIC "${BUILD_METADATA_FILE}")
target_include_directories(${BUILD_METADATA_TARGET} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
add_custom_command(
	TARGET ${BUILD_METADATA_TARGET} PRE_BUILD
	COMMAND "${CMAKE_COMMAND}" -E touch "${BUILD_METADATA_FILE}"
	VERBATIM
)
add_custom_target(GenerateBuildMetadata DEPENDS "${PROJECT_SOURCE_DIR}/${BUILD_METADATA_FILE}")

add_custom_command(
	TARGET ${BUILD_METADATA_TARGET} POST_BUILD
	COMMAND "${CMAKE_COMMAND}" -E cat "${BUILD_METADATA_FILE}"
	COMMENT "Generated build metadata:"
	VERBATIM
)