execute_process(
    COMMAND git rev-parse HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT
    RESULT_VARIABLE GIT_RESULT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT_SHORT
    RESULT_VARIABLE GIT_RESULT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(BUILD_METADATA_FILE "${CMAKE_BINARY_DIR}/src/build-metadata.cpp")
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/build-metadata.cpp.in" 
    "${BUILD_METADATA_FILE}")
add_library(${BUILD_METADATA_LIB} STATIC "${BUILD_METADATA_FILE}")
target_include_directories(${BUILD_METADATA_LIB} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
add_custom_command(
	TARGET ${BUILD_METADATA_LIB} PRE_BUILD
	COMMAND "${CMAKE_COMMAND}" -E touch "${BUILD_METADATA_FILE}"
	VERBATIM
)
add_custom_target(GenerateBuildMetadata DEPENDS "${CMAKE_SOURCE_DIR}/${BUILD_METADATA_FILE}")
