#include <sstream>
#include <algorithm>
#include <string_view>

#include <raylib.h>

#include "game.hpp"
#include "utils.hpp"
#include "save-data.hpp"
#include "snake.hpp"
#include "basics.hpp"

Game::Game() :
	m_stepCount(0), m_score(0), m_startSpeed(SNAKE_START_SPEED), m_speed(m_startSpeed),
	m_timeSinceStep(0.f), m_hasLost(false), m_isPaused(false), m_shouldRestart(false),
	m_restartButtonHovered(false), m_restartButtonHeld(false), m_isSaveDirty(false),
	m_inputQueue(), m_snake(SNAKE_START_LENGTH, *this), m_apples(),
	m_saveData(loadSaveData(SAVE_PATH + "/" + SAVE_FILE)) {

	SetConfigFlags(FLAG_WINDOW_RESIZABLE);
	InitWindow(DEFAULT_SCREEN_SIZE, DEFAULT_SCREEN_SIZE, "Snake");

	rlSetLineWidth(3.f);

	auto icon = LoadImage("resources/icon.png");
	SetWindowIcon(icon);
	UnloadImage(icon);

	// i can only get the monitors size after the window is initialized :( this causes annoying problems
	int const monitorHeight = GetMonitorHeight(GetCurrentMonitor());
	float const resizeRatio = monitorHeight / DEFAULT_DISPLAY_HEIGHT;
	float const newSize = DEFAULT_SCREEN_SIZE * resizeRatio;
	SetWindowSize(newSize, newSize);

	auto const windowPosX = GetWindowPosition().x;
	SetWindowPosition(windowPosX, (monitorHeight - newSize) / 2);

	IMGUI_ONLY(rlImGuiSetup(true));

	SetTargetFPS(60);
}

Game::~Game() {
	IMGUI_ONLY(rlImGuiShutdown());
	CloseWindow();

	if (!m_isSaveDirty) {
		if (!DirectoryExists(SAVE_PATH.c_str())) MakeDirectory(SAVE_PATH.c_str());
		saveData(SAVE_PATH + "/" + SAVE_FILE, m_saveData.highScore);
	}
}

SaveData Game::loadSaveData(std::string_view saveFile) {
	if (FileExists(saveFile.data())) {
		std::string rawFileData = LoadFileText(saveFile.data());
		std::string decoded;
		{
			int base64DecodedSize;
			char const* base64DecodedCStr = reinterpret_cast<char const*>(DecodeDataBase64(rawFileData.c_str(), &base64DecodedSize));
			if (base64DecodedCStr != nullptr) {
				std::string base64Decoded{base64DecodedCStr, static_cast<size_t>(base64DecodedSize)};
				for (char const _char : base64Decoded) decoded.push_back(_char ^ SAVE_DATA_XOR_KEY);
			} else {
				TraceLog(LOG_ERROR, "Failed to decode save data from base64.");
				TraceLog(LOG_INFO, "[DEBUG]");
				TraceLog(LOG_INFO, "Raw corrupted base64 data:\n%s", rawFileData.c_str());
				return 0;
			}
		}

		std::vector<std::string> linesVec{};
		std::istringstream stream{decoded};
		std::string line;
		while (std::getline(stream, line, '\n')) linesVec.push_back(line);
		std::string final;
		for (auto const& str : linesVec) {
			if (!str.empty() && str[0] != '#') {
				final = str;
				break;
			}
		}

		if (final.size() > 3) {
			TraceLog(LOG_ERROR, "Don't cheat! %s is not normal.", final.c_str());
			return -200;
		}
		try {
			return std::stoi(final);
		} catch (std::invalid_argument const&) {
			TraceLog(LOG_ERROR, "Error parsing save data from file.");
			TraceLog(LOG_INFO, "[DEBUG]");
			TraceLog(LOG_INFO, "Got:\n%s", decoded.c_str());
			TraceLog(LOG_INFO, "Parsed:\n%s", final.c_str());
		}
	} else TraceLog(LOG_INFO, "Save File does not exist, defaulting high-score to 0.");
	return 0;
}

void Game::saveData(std::string_view saveFile, SaveData saveData) {
	std::string raw = TextFormat(
		"# This file was automatically generated by the Snake game.\n"
		"# All lines starting with a # will be ignored.\n"
		"# Any change made to this file will be discarded on the next time you start the game.\n"
		"# Although if you're already here you might deserve that little bit of extra score.\n"
		"# (reading the code doesn't count, you lame cheater)\n"
		"%i", saveData
	);
	std::string xored; // xored as in something that had gone through the xor process. https://en.wikipedia.org/wiki/Bitwise_operation#XOR
	for (char const _char : raw) xored.push_back(_char ^ SAVE_DATA_XOR_KEY);
	int _;
	std::string encoded = EncodeDataBase64(reinterpret_cast<unsigned char const*>(xored.c_str()), xored.size(), &_);
	if (!SaveFileText(saveFile.data(), encoded.c_str()))
		TraceLog(LOG_ERROR, "Failed to save the following save data: %s\n", encoded.c_str());
}

void Game::reset() {
	m_stepCount
		= m_score
		= 0;
	m_speed = m_startSpeed;
	m_timeSinceStep = 0.f;
	// m_roundStart = GetTime();
	m_hasLost
		= m_isPaused
		= m_shouldRestart
		= m_restartButtonHovered
		= m_restartButtonHeld
		= false;

	while (!m_inputQueue.empty()) m_inputQueue.pop(); // if only std::queue::clear() existed...

	m_snake.reset();

	Apple firstApple;
	do firstApple = getRandomTile();
	while (std::find(m_snake.m_tiles.begin(), m_snake.m_tiles.end(), firstApple) != m_snake.m_tiles.end());
	m_apples.clear();
	m_apples.push_back(firstApple);
}

bool Game::run() {
	reset();

	bool isWindowMaximized = false;

	static auto screen = LoadRenderTexture(DEFAULT_SCREEN_SIZE, DEFAULT_SCREEN_SIZE);

	while (!WindowShouldClose()) {
		bool hasStepped = false;

		IMGUI_ONLY(hasStepped |= debugGUI());
		hasStepped |= update();

		int const screenHeight = GetScreenHeight();
		float const resizeRatio = screenHeight / DEFAULT_SCREEN_SIZE;
		BeginTextureMode(screen); {
			if (hasStepped || IsWindowResized()) {
				ClearBackground(BLANK);
				draw();
			}
			handleRestartButton(resizeRatio);
		} EndTextureMode();
		BeginDrawing();
		{
			float const actualScreenSize = DEFAULT_SCREEN_SIZE * resizeRatio;
			DrawTexturePro(screen.texture,
				{ 0.f, 0.f, DEFAULT_SCREEN_SIZE, -DEFAULT_SCREEN_SIZE },
				{ 0.f, 0.f, actualScreenSize, actualScreenSize },
				{ 0.f, 0.f }, 0.f, WHITE
			);
		}
		IMGUI_ONLY(rlImGuiEnd());
		EndDrawing();

		if (IsWindowResized()) {
			int newSize = std::min(GetScreenWidth(), GetScreenHeight());
			SetWindowSize(newSize, newSize);
		}
		if (IsWindowMaximized() && !isWindowMaximized) {
			SetWindowPosition(
				(GetMonitorWidth(GetCurrentMonitor()) - GetScreenWidth()) / 2,
				(GetMonitorHeight(GetCurrentMonitor()) - GetScreenHeight()) / 2
			);
			isWindowMaximized = true;
		} else if (!IsWindowMaximized()) isWindowMaximized = false;

		if (IsKeyPressed(KEY_Q)) return false;
		if (IsKeyPressed(KEY_R) || m_shouldRestart) return true;
	}

	return false;
}

void Game::checkDeath() {
	int n = 0;
	for (auto const& tile : m_snake.m_tiles) {
		auto const& nextTile = m_snake.getNextTile();
		auto const& tail =  m_snake.m_tiles.front();
		if (tile == nextTile && tile != tail) {
			m_hasLost = true;
			if (m_snake.m_tiles.size() < 4) TraceLog(LOG_WARNING, "Oops! you are not supposed to die this short!");
			return;
		}
	}
}

void Game::advanceScore() {
	m_score++;
	m_saveData.highScore = std::max(m_saveData.highScore, m_score);
}

void Game::step() {
	m_snake.m_tiles.push_back(m_snake.getNextTile());

	bool pop = true;
	for (auto& apple : m_apples) {
		if (CheckCollisionRecs(
			recFromIndices(m_snake.m_tiles.back(), GRID),
			recFromIndices(apple, GRID))
		) {
			pop = false;
			auto newApple = apple;
			do newApple = getRandomTile();
			while (
				std::find(m_snake.m_tiles.begin(), m_snake.m_tiles.end(), newApple) != m_snake.m_tiles.end() ||
				std::find(m_apples.begin(), m_apples.end(), newApple) != m_apples.end()
			);
			apple = newApple;
			advanceScore();
			m_speed += ACCELERATION_RATE;
		}
	}
	if (pop) m_snake.m_tiles.pop_front();
}

bool Game::update() {
	auto processInput = [&](Direction direction) {
		if (m_inputQueue.size() > 5) return;
		bool changeDirection = false;
		auto lastInput = m_inputQueue.empty() ? m_snake.m_direction : m_inputQueue.back();
		switch (direction) {
			case Up:    if (lastInput != Down  && lastInput != Up   ) changeDirection = true; break;
			case Down:  if (lastInput != Up    && lastInput != Down ) changeDirection = true; break;
			case Left:  if (lastInput != Right && lastInput != Left ) changeDirection = true; break;
			case Right: if (lastInput != Left  && lastInput != Right) changeDirection = true; break;
			default: break;
		}
		if (changeDirection) m_inputQueue.push(direction);
	};

	{
		if (!m_hasLost) {
			switch(GetKeyPressed()) {
				case KEY_K:
				case KEY_W:
				case KEY_UP: processInput(Up); break;
				case KEY_J:
				case KEY_S:
				case KEY_DOWN: processInput(Down); break;
				case KEY_H:
				case KEY_A:
				case KEY_LEFT: processInput(Left); break;
				case KEY_L:
				case KEY_D:
				case KEY_RIGHT: processInput(Right); break;
			}

			if (IsKeyPressed(KEY_SPACE)) m_isPaused = !m_isPaused;

			if (m_score >= m_apples.size() * NEW_APPLE_INTERVAL) {
				Apple newApple;
				do newApple = getRandomTile();
				while (
					std::find(m_snake.m_tiles.begin(), m_snake.m_tiles.end(), newApple) != m_snake.m_tiles.end() ||
					std::find(m_apples.begin(), m_apples.end(), newApple) != m_apples.end()
				);
				m_apples.push_back(newApple);
			}
		}
		m_timeSinceStep += GetFrameTime();
		if (m_timeSinceStep * m_speed > 1) {
			m_stepCount++;
			m_timeSinceStep -= 1 / m_speed;
			if (!m_isPaused && !m_hasLost) {
				Direction prev = m_snake.m_direction;
				if (!m_inputQueue.empty()) {
					m_snake.m_direction = m_inputQueue.front();
					m_inputQueue.pop();
				}
				checkDeath();
				if (m_hasLost) {
					while (!m_inputQueue.empty()) m_inputQueue.pop();
					m_snake.m_direction = prev;
				} else {
					step();
					return true;
				}
			}
		}
	}
	return false;
}

#define DIRECTION_BUTTON(_direction)                                                          \
	if (ImGui::ArrowButton(directionToString(_direction).c_str(), ImGuiDir_##_direction)) {   \
		hasStepped = true;                                                                    \
		m_snake.m_direction = _direction;                                                     \
		step();                                                                               \
		checkDeath();                                                                         \
	}

IMGUI_ONLY(bool Game::debugGUI() {
	bool hasStepped = false;

	rlImGuiBegin();
	ImGui::Begin("Debug Window");

	if (m_shouldRestart) ImGui::Text(
		"restarting in the next frame lol"
		"\nhow are you reading this its too long to be read in 1/60 of a second"
		"\nunless youre reading the code, in which case... yeah...\n"
	);

	auto currentDirection = directionToString(m_snake.m_direction);
	ImGui::Text("Current direction: %s", currentDirection.c_str());
	ImGui::Text("Step count: %i", m_stepCount);
	ImGui::Text("Time since step: %f", m_timeSinceStep);
	if (m_isSaveDirty) ImGui::Text("Save is dirty.");
	if (m_restartButtonHovered) ImGui::Text("Restart button is hovered.");
	if (m_restartButtonHeld) ImGui::Text("Restart button is held.");
	ImGui::NewLine();

	ImGui::Checkbox("Pause game", &m_isPaused);

	if (ImGui::Button("Step")) {
		hasStepped = true;
		step();
		checkDeath();
	}
	ImGui::SameLine();
	if (ImGui::Button("Expand")) {
		hasStepped = true;
		m_snake.m_tiles.push_back(m_snake.getNextTile());
		checkDeath();
	}

	ImGui::NewLine();
	ImGui::Indent(20.f);

	ImGui::Indent(30.f);
	DIRECTION_BUTTON(Up);
	ImGui::Unindent(30.f);

	DIRECTION_BUTTON(Left);
	ImGui::SameLine(0.f, 36.f);
	DIRECTION_BUTTON(Right);

	ImGui::Indent(30.f);
	DIRECTION_BUTTON(Down);
	ImGui::Unindent(30.f);

	ImGui::Unindent(20.f);
	ImGui::NewLine();

	if (ImGui::Button("+")) {
		advanceScore();
		m_isSaveDirty = true;
	}
	ImGui::SameLine();
	ImGui::Text("Advance score (disables saving to file)");

	ImGui::Text("Start length");
	size_t min = 1; size_t max = 15;
	ImGui::SliderScalar("##start-length", ImGuiDataType_U64, &m_snake.m_startLength, &min, &max, "%d");

	ImGui::Text("Start speed");
	ImGui::SliderFloat("##start-speed", &m_startSpeed, 0, 50);

	ImGui::Text("Current speed");
	ImGui::SliderFloat("##current-speed", &m_speed, 0, 50);

	ImGui::End();
	return hasStepped;
})

void Game::handleRestartButton(float resizeRatio) {
	static auto const restartBtn = [&] {
		auto image = GenImageColor(2 * RESTART_BUTTON_SIZE, 2 * RESTART_BUTTON_SIZE, BLANK);
		ImageDrawCircleV(&image, { RESTART_BUTTON_SIZE, RESTART_BUTTON_SIZE }, RESTART_BUTTON_SIZE, RESTART_BUTTON_OUTER_COLOR);
		ImageDrawCircleV(&image, { RESTART_BUTTON_SIZE, RESTART_BUTTON_SIZE }, RESTART_BUTTON_SIZE * .65f, RESTART_BUTTON_INNER_COLOR);
		ImageDrawCircleV(&image, { RESTART_BUTTON_SIZE, RESTART_BUTTON_SIZE }, RESTART_BUTTON_SIZE * .4f, RESTART_BUTTON_OUTER_COLOR);
		ImageDrawTriangle(&image,
			{ RESTART_BUTTON_SIZE * .15f, RESTART_BUTTON_SIZE / 2 },
			{ RESTART_BUTTON_SIZE * .15f, RESTART_BUTTON_SIZE * 1.5f },
			{ RESTART_BUTTON_SIZE, RESTART_BUTTON_SIZE },
		RESTART_BUTTON_OUTER_COLOR);
		ImageDrawTriangle(&image,
			{ RESTART_BUTTON_SIZE * .38f, RESTART_BUTTON_SIZE * .57f },
			{ RESTART_BUTTON_SIZE * .4f,  RESTART_BUTTON_SIZE * .92f },
			{ RESTART_BUTTON_SIZE * .75f, RESTART_BUTTON_SIZE * .89f },
		RESTART_BUTTON_INNER_COLOR);

		auto ret = LoadTextureFromImage(image);
		UnloadImage(image);
		return ret;
	}();
	if (m_hasLost) {
		if (CheckCollisionPointCircle(
			// needed because otherwise it checks for clicks in the unresized original position
			GetMousePosition(), RESTART_BUTTON_INFO.center * resizeRatio,
			// here too
			RESTART_BUTTON_INFO.radius * resizeRatio
		)) {
			if (!m_restartButtonHovered) {
				m_restartButtonHovered = true;
				draw();
				DrawTextureV(restartBtn, RESTART_BUTTON_INFO.origin, WHITE);
			}
			if (!m_restartButtonHeld && IsMouseButtonPressed(0)) {
				m_restartButtonHeld = true;
				DrawCircleV(RESTART_BUTTON_INFO.center, RESTART_BUTTON_INFO.radius, {.a = 70});
			}
			DrawCircleLinesV(RESTART_BUTTON_INFO.center, RESTART_BUTTON_INFO.radius - 1.5f, RAYWHITE);
			if (IsMouseButtonReleased(0) && m_restartButtonHeld) m_shouldRestart = true;
		} else {
			m_restartButtonHeld = m_restartButtonHovered = false;
			draw();
			DrawTextureV(restartBtn, RESTART_BUTTON_INFO.origin, WHITE);
		}
	}
}

void Game::draw() const {
	ClearBackground({ 40, 140, 50, 255 });

	static Color constexpr MAIN_COLOR = { 160, 255, 96, 255 };
	static Color constexpr ALT_COLOR = { 150, 235, 85, 255 };
	{
		static auto const bg = [&] {
			RenderTexture2D target = LoadRenderTexture(DEFAULT_SCREEN_SIZE, DEFAULT_SCREEN_SIZE);
			BeginTextureMode(target);
			bool alternateColor = false;
			for (auto const& line : GRID) {
				for (auto const& rect : line) {
					DrawRectangleRec(rect, alternateColor ? ALT_COLOR : MAIN_COLOR);
					alternateColor = !alternateColor;
				}
			}
			EndTextureMode();
			return target.texture;
		}();
		DrawTextureV(bg, { }, WHITE);
	}

	{
		static auto const apple = [&] {
			auto image = LoadImage("resources/apple.png");
			ImageResize(&image, USED_TILE_SPACE, USED_TILE_SPACE);
			auto ret = LoadTextureFromImage(image);
			UnloadImage(image);
			return ret;
		}();
		for (auto const& applePos : m_apples) {
			auto const& appleRec = recFromIndices(applePos, GRID);
			DrawTextureV(apple, { appleRec.x + TILE_EDGE_SIZE, appleRec.y + TILE_EDGE_SIZE }, WHITE);
		}
	}

	m_snake.draw();

	if (m_hasLost) {
		static auto const loseText = [&] {
			auto image = ImageTextEx(GetFontDefault(),
				"You lost!", 125.f, 1.f, BLACK
			);
			auto ret = LoadTextureFromImage(image);
			UnloadImage(image);
			return ret;
		}();
		DrawTextureV(loseText, {
			(DEFAULT_SCREEN_SIZE - loseText.width) / 2,
			(DEFAULT_SCREEN_SIZE - loseText.height) / 2 - 50.f,
		}, WHITE);
	}

	drawOverlay();
}

void Game::drawOverlay() const {
	{
		static auto const apple = [&] {
			auto image = LoadImage("resources/apple.png");
			ImageResize(&image, FREE_SPACE - 20.f, FREE_SPACE - 20.f);
			auto ret = LoadTextureFromImage(image);
			UnloadImage(image);
			return ret;
		}();
		DrawTextureV(apple, {
			DEFAULT_SCREEN_SIZE - 100.f,
			(FREE_SPACE - apple.height) / 2,
		}, WHITE);
		DrawTextEx(GetFontDefault(),
			TextFormat("%i", m_score),
			{ DEFAULT_SCREEN_SIZE - 60.f, 15.f }, 25.f, 2.5f, BLACK
		);

		static auto const trophy = [&] {
			auto image = LoadImage("resources/trophy.png");
			ImageResize(&image, FREE_SPACE - 20.f, FREE_SPACE - 20.f);
			auto ret = LoadTextureFromImage(image);
			UnloadImage(image);
			return ret;
		}();
		DrawTextureV(trophy, {
			DEFAULT_SCREEN_SIZE - 200.f,
			(FREE_SPACE - trophy.height) / 2,
		}, WHITE);
		DrawTextEx(GetFontDefault(),
			TextFormat("%i", m_saveData.highScore),
			{ DEFAULT_SCREEN_SIZE - 160.f, 15.f },
			25.f, 2.5f, BLACK
		);
	}
	{
		static float constexpr ARROW_SIZE = FREE_SPACE - 20.f;
		static auto const arrow = [&] {
			auto image = GenImageColor(ARROW_SIZE, ARROW_SIZE, BLANK);
			ImageDrawTriangle(&image,
				{ 0.f, ARROW_SIZE / 2 },
				{ ARROW_SIZE / 2, 0.f },
				{ ARROW_SIZE, ARROW_SIZE / 2 },
			BLACK);
			ImageDrawRectangleRec(&image, { 7.5f, ARROW_SIZE / 2, ARROW_SIZE / 2, ARROW_SIZE / 2 }, BLACK);

			auto ret = LoadTextureFromImage(image);
			UnloadImage(image);
			return ret;
		}();

		DrawTextureEx(arrow,
			{ DEFAULT_SCREEN_SIZE / 2 - ARROW_SIZE / 2, 10.f },
			0.f,   1.f,
			(IsKeyDown(KEY_UP) || IsKeyDown(KEY_W)) && !m_hasLost ? BLACK : Color{.a = 70}
		);
		DrawTextureEx(arrow,
			{ DEFAULT_SCREEN_SIZE / 2 + ARROW_SIZE / 2, DEFAULT_SCREEN_SIZE - 10.f },
			180.f, 1.f,
			(IsKeyDown(KEY_DOWN) || IsKeyDown(KEY_S))  && !m_hasLost ? BLACK : Color{.a = 70}
		);
		DrawTextureEx(arrow,
			{ 10.f, DEFAULT_SCREEN_SIZE / 2 + ARROW_SIZE / 2 },
			-90.f, 1.f,
			(IsKeyDown(KEY_LEFT) || IsKeyDown(KEY_A))  && !m_hasLost ? BLACK : Color{.a = 70}
		);
		DrawTextureEx(arrow,
			{ DEFAULT_SCREEN_SIZE - 10.f, DEFAULT_SCREEN_SIZE / 2 - ARROW_SIZE / 2 },
			90.f,  1.f,
			(IsKeyDown(KEY_RIGHT) || IsKeyDown(KEY_D)) && !m_hasLost ? BLACK : Color{.a = 70}
		);
	}
}
