#if defined(_WIN32) && defined(CMAKE_RELEASE_BUILD)
// holy shit i hate raylib + windows
// it compiles so shut up
#define _WINGDI_
#define LF_FACESIZE 32
#define _WINUSER_
#define _APISETCONSOLEL3_
#define _WINSPOOL_
#define _OLE2_H_
#define _INC_COMMDLG
#define _IMM_SDK_DEFINED_
#define _PLAYSOUNDAPI_H_
#include <windows.h>
#undef min
int main();
int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) { return main(); }
#endif

#include <algorithm>
#include <array>
#include <deque>
#include <queue>
#include <random>
#include <sstream>
#include <string>

#include <raylib.h>
#include <raymath.h>
#include <rlgl.h>
#ifndef CMAKE_RELEASE_BUILD
	#include <imgui.h>
	#include <rlImGui.h>
	#define DEBUG_ONLY(...) __VA_ARGS__
#else
	#define DEBUG_ONLY(...)
#endif

int constexpr GRID_SIZE = 21;
float constexpr TILE_SIZE = 40.f;
float constexpr FREE_SPACE = 50.f;
float constexpr DEFAULT_SCREEN_SIZE = GRID_SIZE * TILE_SIZE + FREE_SPACE * 2;
float constexpr DEFAULT_MONITOR_HEIGHT = 1080.f;

char constexpr SAVE_FILE[] = "save.dat";
int8_t constexpr SAVE_DATA_XOR_KEY = 47;

int getSavedMaxScore();
void saveMaxScore(int maxScore);

using Grid = std::array<std::array<Rectangle, GRID_SIZE>, GRID_SIZE>;

using Direction = enum { Up, Down, Left, Right, };
inline std::string constexpr directionToString(Direction direction) {
	switch (direction) {
		case Up:    return "up";
		case Down:  return "down";
		case Left:  return "left";
		case Right: return "right";
	}
	return "";
}

using Tile = std::array<int, 2>;

struct Snake {
	using Tiles = std::deque<Tile>;
	Tiles tiles;

	Tile getNextTile() const;
	void step(Grid& grid);

	Direction direction;
	
	using Apple = Tile;
	std::vector<Apple> apples;

	int score;
	static int s_maxScore;
};

int Snake::s_maxScore = 0;

void draw(Grid const& grid, Snake const& snake, bool hasLost);

static inline Rectangle       constexpr& rectFromIndices(Tile const& indices, Grid&       grid) { return grid[indices[0]][indices[1]]; }
static inline Rectangle const constexpr& rectFromIndices(Tile const& indices, Grid const& grid) { return grid[indices[0]][indices[1]]; }

static std::random_device rd;
static std::mt19937 e{rd()};
static std::uniform_int_distribution<int> dist{0, GRID_SIZE - 1};
	
bool startGame();

int main() {
#ifdef VERBOSE_LOGGING
	DEBUG_ONLY(SetTraceLogLevel(LOG_DEBUG));
#endif

	Snake::s_maxScore = getSavedMaxScore();

	SetConfigFlags(FLAG_WINDOW_RESIZABLE);
	InitWindow(DEFAULT_SCREEN_SIZE, DEFAULT_SCREEN_SIZE, "Snake");

	auto icon = LoadImage("resources/icon.png");
	SetWindowIcon(icon);
	UnloadImage(icon);

	// i can only get the monitors size after the window is initialized :( this causes annoying problems
	int const monitorHeight = GetMonitorHeight(GetCurrentMonitor());
	float const resizeRatio = monitorHeight / DEFAULT_MONITOR_HEIGHT;
	float const newSize = DEFAULT_SCREEN_SIZE * resizeRatio;
	SetWindowSize(newSize, newSize);

	auto const windowPosX = GetWindowPosition().x;
	SetWindowPosition(windowPosX, (monitorHeight - newSize) / 2);

	rlSetLineWidth(3.f);
	DEBUG_ONLY(rlImGuiSetup(true));

	SetTargetFPS(60);

	while (startGame()) continue;

	DEBUG_ONLY(rlImGuiShutdown());
	CloseWindow();

	saveMaxScore(Snake::s_maxScore);

	return 0;
}

int getSavedMaxScore() {
	if (FileExists(SAVE_FILE)) {
		std::string rawFileData = LoadFileText(SAVE_FILE);
		std::string decoded;
		{
			int base64DecodedSize;
			char const* base64DecodedCStr = (char const*)DecodeDataBase64(rawFileData.c_str(), &base64DecodedSize);
			if (base64DecodedCStr != nullptr) {
				std::string base64Decoded{base64DecodedCStr, (size_t)base64DecodedSize};
				for (char const char_ : base64Decoded) decoded.push_back(char_ ^ SAVE_DATA_XOR_KEY);
			} else {
				TraceLog(LOG_ERROR, "Failed to decode max score from base64.");
				TraceLog(LOG_INFO, "[DEBUG]");
				TraceLog(LOG_INFO, "Raw corrupted base64 data:\n%s", rawFileData.c_str());
				return 0;
			}
		}

		std::vector<std::string> linesVec{};
		std::istringstream stream{decoded};
		std::string line;
		while (std::getline(stream, line, '\n')) linesVec.push_back(line);
		std::string final;
		for (auto const& str : linesVec) {
			if (!str.empty() && str[0] != '#') {
				final = str;
				break;
			}
		}

		if (final.size() > 3) {
			TraceLog(LOG_ERROR, "Don't cheat! %s is not normal.", final.c_str());
			return -200;
		}
		try {
			return std::stoi(final);
		} catch (std::invalid_argument const&) {
			TraceLog(LOG_ERROR, "Error parsing Max Score from file.");
			TraceLog(LOG_INFO, "[DEBUG]");
			TraceLog(LOG_INFO, "Got:\n%s", decoded.c_str());
			TraceLog(LOG_INFO, "Parsed:\n%s", final.c_str());
		}
	} else TraceLog(LOG_WARNING, "Save File does not exist, defaulting to 0.");
	return 0;
}

void saveMaxScore(int maxScore) {
	std::string raw = TextFormat(
		"# This file was automatically generated by the Snake game.\n"
		"# All lines starting with a # will be ignored.\n"
		"# Any change made to this file will be discarded on the next time you start the game.\n"
		"# Although if you're already here you might deserve that little bit of extra score.\n"
		"# (reading the code doesn't count, you lame cheater)\n"
		"%i", maxScore
	);
	std::string xored; // xored as in something that had gone through the xor process. https://en.wikipedia.org/wiki/Bitwise_operation#XOR
	for (char const char_ : raw) xored.push_back(char_ ^ SAVE_DATA_XOR_KEY);
	int _;
	std::string encoded = EncodeDataBase64((unsigned char const*)xored.c_str(), xored.size(), &_);
	if (!SaveFileText(SAVE_FILE, encoded.c_str())) 
		TraceLog(LOG_ERROR, "Failed to save the following max score data: %s\n", encoded.c_str());
}

bool startGame() {
	static Tile constexpr START_POS = { 12, 10, };
	
	bool restart = false;

	Grid grid{};
	for (int i = 0; i < GRID_SIZE; i++) {
		for (int j = 0; j < GRID_SIZE; j++) {
			rectFromIndices({ j, i, }, grid) = {
				FREE_SPACE + j * TILE_SIZE,
				FREE_SPACE + i * TILE_SIZE,
				TILE_SIZE, TILE_SIZE,
			};
		}
	}


	Snake snake = { { }, Left, { }, 0, };
	snake.tiles.push_back(START_POS);
	snake.apples.push_back({ dist(e), dist(e), });

	static int constexpr START_LENGTH = 3;
	for (int i = 1; i < START_LENGTH; i++) snake.tiles.push_back(snake.getNextTile());
	
	bool paused = false;
	bool hasLost = false;

	auto checkDeath = [&] {
		if (snake.tiles.size() < 5) return; // no more of this
		int n = 0;
		for (auto const& tile : snake.tiles) if (tile == snake.getNextTile() && tile != snake.tiles.front()) {
			hasLost = true;
			break;
		}
	};

	std::queue<Direction> inputQueue{};
	auto processInput = [&](Direction direction) {
		if (inputQueue.size() > 5) return;
		bool changeDir = false;
		auto checkDir = inputQueue.empty() ? snake.direction : inputQueue.front();
		switch (direction) {
			case Up:    if (checkDir != Down  && checkDir != Up   ) changeDir = true; break;
			case Down:  if (checkDir != Up    && checkDir != Down ) changeDir = true; break;
			case Left:  if (checkDir != Right && checkDir != Left ) changeDir = true; break;
			case Right: if (checkDir != Left  && checkDir != Right) changeDir = true; break;
		}
		if (changeDir) inputQueue.push(direction);
	};

	int speed = 15;
	int stepCount = 0;
	double const gameStart = GetTime();

	bool restartButtonHeld = false;
	bool restartButtonHovered = false;

	int lastSpeedup = 0;
	int lastNewApple = 0;

	bool isWindowMaximized = false;

	static auto screen = LoadRenderTexture(DEFAULT_SCREEN_SIZE, DEFAULT_SCREEN_SIZE);
	while (!WindowShouldClose()) {
		bool hasStepped = false;

		{
			if (!hasLost) {
				if      (IsKeyPressed(KEY_UP))    processInput(Up);
				else if (IsKeyPressed(KEY_DOWN))  processInput(Down);
				else if (IsKeyPressed(KEY_LEFT))  processInput(Left);
				else if (IsKeyPressed(KEY_RIGHT)) processInput(Right);

				if (IsKeyPressed(KEY_SPACE)) paused = !paused;

				static int constexpr NEW_APPLE_INTERVAL = 10;
				if (snake.score >= lastNewApple + NEW_APPLE_INTERVAL) {
					lastNewApple += NEW_APPLE_INTERVAL;
					Snake::Apple newApple;
					do newApple = { dist(e), dist(e), };
					while (
						std::find(snake.tiles.begin(), snake.tiles.end(), newApple) != snake.tiles.end() ||
						std::find(snake.apples.begin(), snake.apples.end(), newApple) != snake.apples.end()
					); 
					snake.apples.push_back(newApple);
				}
				static int constexpr SPEEDUP_INTERVAL = 2;
				if (snake.score >= lastSpeedup + SPEEDUP_INTERVAL) {
					lastSpeedup += SPEEDUP_INTERVAL;
					speed++;
					stepCount = std::floor((GetTime() - gameStart) * speed); // to prevent sudden speed bursts
				}
			}
			if ((GetTime() - gameStart) * speed > stepCount) {
				stepCount++;
				if (!paused && !hasLost) {
					Direction prev = snake.direction;
					if (!inputQueue.empty()) {
						snake.direction = inputQueue.front();
						inputQueue.pop();
					}
					checkDeath();
					if (hasLost) {
						while (!inputQueue.empty()) inputQueue.pop();
						snake.direction = prev;
					} else {
						snake.step(grid);
						hasStepped = true;
					}
				}
			}
		}

		{
		#ifndef CMAKE_RELEASE_BUILD // has to be #ifdef-ed because preprocessors in macro expansions (DEBUG_ONLY macro) break MSVC
			rlImGuiBegin();
			ImGui::Begin("Debug Window");

			ImGui::Checkbox("Pause game", &paused);

			auto currentDirection = directionToString(snake.direction);
			ImGui::Text("Current direction: %s", currentDirection.c_str());

			if (ImGui::Button("Step")) {
				hasStepped = true;
				snake.step(grid);
				checkDeath();
			}
			ImGui::SameLine();
			if (ImGui::Button("Expand")) {
				hasStepped = true;
				snake.tiles.push_back(snake.getNextTile());
				checkDeath();
			}

		#define DIRECTION_BUTTON(direction_)                                                          \
			if (ImGui::ArrowButton(directionToString(direction_).c_str(), ImGuiDir_##direction_)) {   \
				hasStepped = true;                                                                    \
				snake.direction = direction_;                                                         \
				snake.step(grid);                                                                     \
				checkDeath();                                                                         \
			}                                                                                         \
			ImGui::SameLine()
			
			DIRECTION_BUTTON(Up);
			DIRECTION_BUTTON(Down);
			DIRECTION_BUTTON(Left);
			DIRECTION_BUTTON(Right);

			ImGui::NewLine();

			ImGui::Text("Steps per second");
			ImGui::SliderInt("", &speed, 0, 50);
			
			ImGui::End();
		#endif
		}

		int const screenHeight = GetScreenHeight();
		float const resizeRatio = screenHeight / DEFAULT_SCREEN_SIZE;
		BeginDrawing();
		{
			BeginTextureMode(screen); {
				if (hasStepped || IsWindowResized()) {
					ClearBackground(BLANK);
					draw(grid, snake, hasLost);
				}

				{
					static float constexpr RESTART_BTN_RADIUS = 75.f;
					static auto const restartBtn = [&] {
						static Color constexpr OUTER_COLOR = { 0, 208, 51, 255 };
						static Color constexpr INNER_COLOR = { 220, 220, 220, 255, };

						auto image = GenImageColor(2 * RESTART_BTN_RADIUS, 2 * RESTART_BTN_RADIUS, BLANK);
						ImageDrawCircleV(&image, { RESTART_BTN_RADIUS, RESTART_BTN_RADIUS, }, RESTART_BTN_RADIUS, OUTER_COLOR);
						ImageDrawCircleV(&image, { RESTART_BTN_RADIUS, RESTART_BTN_RADIUS, }, RESTART_BTN_RADIUS * .65f, INNER_COLOR);
						ImageDrawCircleV(&image, { RESTART_BTN_RADIUS, RESTART_BTN_RADIUS, }, RESTART_BTN_RADIUS * .4f, OUTER_COLOR);
						ImageDrawTriangle(&image,
							{ RESTART_BTN_RADIUS * .15f, RESTART_BTN_RADIUS / 2, },
							{ RESTART_BTN_RADIUS * .15f, RESTART_BTN_RADIUS * 1.5f, },
							{ RESTART_BTN_RADIUS, RESTART_BTN_RADIUS, },
						OUTER_COLOR);
						ImageDrawTriangle(&image,
							{ RESTART_BTN_RADIUS * .38f, RESTART_BTN_RADIUS * .57f },
							{ RESTART_BTN_RADIUS * .4f,  RESTART_BTN_RADIUS * .92f, },
							{ RESTART_BTN_RADIUS * .75f, RESTART_BTN_RADIUS * .89f, },
						INNER_COLOR);

						auto ret = LoadTextureFromImage(image);
						UnloadImage(image);
						return ret;
					}();
					static struct {
						Vector2 origin;
						Vector2 center;
						float radius;
					} constexpr restartBtnCircle = { {
							DEFAULT_SCREEN_SIZE / 2 - RESTART_BTN_RADIUS,
							DEFAULT_SCREEN_SIZE / 2,
						}, {
							DEFAULT_SCREEN_SIZE / 2,
							DEFAULT_SCREEN_SIZE / 2 + RESTART_BTN_RADIUS,
						}, RESTART_BTN_RADIUS,
					};
					
					static auto const loseText = [&] {
						auto image = ImageTextEx(GetFontDefault(),
							"You lost!", 125.f, 1.f, BLACK
						);
						auto ret = LoadTextureFromImage(image);
						UnloadImage(image);
						return ret;
					}();

					if (hasLost) {
						if (CheckCollisionPointCircle(
							// needed because otherwise it checks for clicks in the unresized original position
							GetMousePosition(), restartBtnCircle.center * resizeRatio,
							// here too
							restartBtnCircle.radius * resizeRatio 
						)) {
							if (!restartButtonHovered) {
								restartButtonHovered = true;
								draw(grid, snake, hasLost);
								DrawTextureV(loseText, {
									(DEFAULT_SCREEN_SIZE - loseText.width) / 2,
									(DEFAULT_SCREEN_SIZE - loseText.height) / 2 - 50.f,
								}, WHITE);
								DrawTextureV(restartBtn, restartBtnCircle.origin, WHITE);
							}
							if (!restartButtonHeld && IsMouseButtonPressed(0)) {
								restartButtonHeld = true;
								DrawCircleV(restartBtnCircle.center, restartBtnCircle.radius, {.a = 70}); 
							}
							DrawCircleLinesV(restartBtnCircle.center, restartBtnCircle.radius - 1.5f, RAYWHITE);
							if (IsMouseButtonReleased(0) && restartButtonHeld) restart = true;
						} else {
							restartButtonHeld = restartButtonHovered = false;
							draw(grid, snake, hasLost);
							DrawTextureV(loseText, {
								(DEFAULT_SCREEN_SIZE - loseText.width) / 2,
								(DEFAULT_SCREEN_SIZE - loseText.height) / 2 - 50.f,
							}, WHITE);
							DrawTextureV(restartBtn, restartBtnCircle.origin, WHITE);
						}
					}
				}
			} EndTextureMode();
			float const actualScreenSize = DEFAULT_SCREEN_SIZE * resizeRatio;
			DrawTexturePro(screen.texture,
				{ 0.f, 0.f, DEFAULT_SCREEN_SIZE, -DEFAULT_SCREEN_SIZE, },
				{ 0.f, 0.f, actualScreenSize, actualScreenSize, },
				{ 0.f, 0.f, }, 0.f, WHITE
			);
		}

		DEBUG_ONLY(rlImGuiEnd());
		EndDrawing();

		if (IsWindowResized()) {
			int newSize = std::min(GetScreenWidth(), GetScreenHeight());
			SetWindowSize(newSize, newSize);
		}
		if (IsWindowMaximized() && !isWindowMaximized) {
			SetWindowPosition(
				(GetMonitorWidth(GetCurrentMonitor()) - GetScreenWidth()) / 2, 
				(GetMonitorHeight(GetCurrentMonitor()) - GetScreenHeight()) / 2
			);
			isWindowMaximized = true;
		} else if (!IsWindowMaximized()) isWindowMaximized = false;

		if (restart) return true;
	}

	return false;
}

void draw(Grid const& grid, Snake const& snake, bool hasLost) {
	static float constexpr TILE_EDGE_SIZE = TILE_SIZE / 8;
	static float constexpr USED_TILE_SPACE = TILE_SIZE - TILE_EDGE_SIZE * 2;
	ClearBackground({ 40, 140, 50, 255, });

	static Color constexpr MAIN_COLOR = { 160, 255, 96, 255, };
	static Color constexpr ALT_COLOR = { 150, 235, 85, 255, };
	{
		static auto const bg = [&] {
			RenderTexture2D target = LoadRenderTexture(DEFAULT_SCREEN_SIZE, DEFAULT_SCREEN_SIZE);
			BeginTextureMode(target);
			bool alternateColor = false;
			for (auto const& line : grid) {
				for (auto const& rect : line) {
					DrawRectangleRec(rect, alternateColor ? ALT_COLOR : MAIN_COLOR);
					alternateColor = !alternateColor;
				}
			}
			EndTextureMode();
			return target.texture;
		}();
		DrawTextureV(bg, { }, WHITE);
	}

	{
		static auto const apple = [&] {
			auto image = LoadImage("resources/apple.png");
			ImageResize(&image, USED_TILE_SPACE, USED_TILE_SPACE);
			auto ret = LoadTextureFromImage(image);
			UnloadImage(image);
			return ret;
		}();
		for (auto const& applePos : snake.apples) {
			auto const& appleRect = rectFromIndices(applePos, grid);
			DrawTextureV(apple, { appleRect.x + TILE_EDGE_SIZE, appleRect.y + TILE_EDGE_SIZE, }, WHITE);
		}
	}

	{
		auto const& head = snake.tiles.back();
		int i = -1;
		for (auto const& tile : snake.tiles) {
			i++;
			auto const& originalRect = rectFromIndices(tile, grid);
			bool willTeleport = false;
			bool didTeleport = false;
			auto drawRect = Rectangle{
				originalRect.x + TILE_EDGE_SIZE, originalRect.y + TILE_EDGE_SIZE,
				USED_TILE_SPACE, USED_TILE_SPACE,
			}; // just a square in the middle of the tile unless told otherwise
			{
				Direction forwardsDirection;
				if (i < snake.tiles.size() - 1) {
					auto const& nextTile = snake.tiles[i + 1];
					auto const nextDiff = std::array{ nextTile[0] - tile[0], nextTile[1] - tile[1], };
					if (abs(nextDiff[0]) > 1 || abs(nextDiff[1]) > 1) {
						willTeleport = true;
						switch (nextDiff[0]) {
							case GRID_SIZE - 1:
							case 1: forwardsDirection = Left; break;
							case -(GRID_SIZE - 1):
							case -1: forwardsDirection = Right; break;
							case 0: switch (nextDiff[1]) {
								case GRID_SIZE - 1:
								case 1: forwardsDirection = Up; break;
								case -(GRID_SIZE - 1):
								case -1: forwardsDirection = Down; break;
							} break;
						}
					}
				}
				Direction backwardsDirection;
				if (i > 0) { // only the first tile doesnt connect backwards
					auto const& prevTile = snake.tiles[i - 1];
					auto const prevDiff = std::array{ prevTile[0] - tile[0], prevTile[1] - tile[1], };
					if (abs(prevDiff[0]) > 1 || abs(prevDiff[1]) > 1) didTeleport = true;
					switch (prevDiff[0]) {
						case GRID_SIZE - 1:
						case -1: backwardsDirection = Left; break;
						case -(GRID_SIZE - 1):
						case 1: backwardsDirection = Right; break;
						case 0: switch (prevDiff[1]) {
							case GRID_SIZE - 1:
							case -1: backwardsDirection = Up; break;
							case -(GRID_SIZE - 1):
							case 1: backwardsDirection = Down; break;
						} break;
					}
				}

				if (didTeleport) { // it should connect to the border backwards
					switch (backwardsDirection) {
						case Up:    drawRect.y      -= TILE_EDGE_SIZE;
						case Down:  drawRect.height += TILE_EDGE_SIZE; break;
						case Left:  drawRect.x      -= TILE_EDGE_SIZE;
						case Right: drawRect.width  += TILE_EDGE_SIZE; break;
					}
				} else if (i > 0) { // it should connect to the previous tile
					switch (backwardsDirection) {
						case Up:    drawRect.y       -= 2 * TILE_EDGE_SIZE;
						case Down:  drawRect.height  += 2 * TILE_EDGE_SIZE; break;
						case Left:  drawRect.x       -= 2 * TILE_EDGE_SIZE;
						case Right: drawRect.width   += 2 * TILE_EDGE_SIZE; break;
					}
				}

				static Color constexpr MAIN_SNAKE_COLOR = { 0, 70, 145, 255, };
				DrawRectangleRec(drawRect, MAIN_SNAKE_COLOR);

				DEBUG_ONLY(
					TraceLog(LOG_DEBUG, "Tile %i:", i);
					TraceLog(LOG_DEBUG, "\t\tForwards Direction:  %s", i < snake.tiles.size() - 1 ? directionToString(forwardsDirection).c_str() : "undefined");
					TraceLog(LOG_DEBUG, "\t\tBackwards Direction: %s", i > 0 ? directionToString(backwardsDirection).c_str() : "undefined");
					TraceLog(LOG_DEBUG, "\t\tDraw Rect: %f, %f, %f, %f", drawRect.x, drawRect.y, drawRect.width, drawRect.height);
				)

				if (willTeleport) { // it should connect to the border forwards
					Rectangle forwardsRect;
					switch (forwardsDirection) {
						case Up: forwardsRect = {
							originalRect.x + TILE_EDGE_SIZE,
							originalRect.y,
							USED_TILE_SPACE,
							TILE_EDGE_SIZE,
						}; break;
						case Down: forwardsRect = {
							originalRect.x + TILE_EDGE_SIZE,
							drawRect.y + drawRect.height,
							USED_TILE_SPACE,
							TILE_EDGE_SIZE,
						}; break;
						case Left: forwardsRect = {
							originalRect.x,
							originalRect.y + TILE_EDGE_SIZE,
							TILE_EDGE_SIZE,
							USED_TILE_SPACE,
						}; break;
						case Right: forwardsRect = {
							drawRect.x + drawRect.width,
							originalRect.y + TILE_EDGE_SIZE,
							TILE_EDGE_SIZE,
							USED_TILE_SPACE,
						}; break;
					}
					DrawRectangleRec(forwardsRect, MAIN_SNAKE_COLOR);
					DEBUG_ONLY(TraceLog(LOG_DEBUG, 
						"\t\tForwards Rect: %f, %f, %f, %f", 
						forwardsRect.x, forwardsRect.y, 
						forwardsRect.width, forwardsRect.height
					));
				}
			}
			if (tile == head) {
				auto const& thirdToLast = snake.tiles[i - 2];
				auto gradientRect = drawRect;
				if (
					// we dont want the gradient to go beyond the borders of the screen
					!didTeleport &&
					// i tried to add a corner gradient to make it look better but it didnt work so
					(head[0] == thirdToLast[0] || head[1] == thirdToLast[1])
				) {
					switch (snake.direction) {
						case Down:  gradientRect.y      -= TILE_SIZE;
						case Up:    gradientRect.height += TILE_SIZE; break;
						case Right: gradientRect.x      -= TILE_SIZE;
						case Left:  gradientRect.width  += TILE_SIZE; break;
					}
				}
				static Color constexpr GRADIENT_COLOR = BLUE;
				switch (snake.direction) {
					case Up:    DrawRectangleGradientEx(gradientRect, GRADIENT_COLOR, BLANK, BLANK, GRADIENT_COLOR); break;
					case Down:  DrawRectangleGradientEx(gradientRect, BLANK, GRADIENT_COLOR, GRADIENT_COLOR, BLANK); break;
					case Left:  DrawRectangleGradientEx(gradientRect, GRADIENT_COLOR, GRADIENT_COLOR, BLANK, BLANK); break;
					case Right: DrawRectangleGradientEx(gradientRect, BLANK, BLANK, GRADIENT_COLOR, GRADIENT_COLOR); break;
				}
			}

			DEBUG_ONLY(DrawTextEx(GetFontDefault(),
				TextFormat("%i", i),
				{ originalRect.x + TILE_EDGE_SIZE + 5.f, originalRect.y + TILE_EDGE_SIZE + 5.f, },
				25.f, 2.5f, { 200, 200, 200, 200, }
			));
		}
	}
	{
		static auto const apple = [&] {
			auto image = LoadImage("resources/apple.png");
			ImageResize(&image, FREE_SPACE - 20.f, FREE_SPACE - 20.f);
			auto ret = LoadTextureFromImage(image);
			UnloadImage(image);
			return ret;
		}();
		DrawTextureV(apple, {
			DEFAULT_SCREEN_SIZE - 100.f,
			(FREE_SPACE - apple.height) / 2,
		}, WHITE);
		DrawTextEx(GetFontDefault(),
			TextFormat("%i", snake.score),
			{ DEFAULT_SCREEN_SIZE - 60.f, 15.f, }, 25.f, 2.5f, BLACK
		);

		static auto const trophy = [&] {
			auto image = LoadImage("resources/trophy.png");
			ImageResize(&image, FREE_SPACE - 20.f, FREE_SPACE - 20.f);
			auto ret = LoadTextureFromImage(image);
			UnloadImage(image);
			return ret;
		}();
		DrawTextureV(trophy, {
			DEFAULT_SCREEN_SIZE - 200.f,
			(FREE_SPACE - trophy.height) / 2,
		}, WHITE);
		DrawTextEx(GetFontDefault(),
			TextFormat("%i", Snake::s_maxScore),
			{ DEFAULT_SCREEN_SIZE - 160.f, 15.f, },
			25.f, 2.5f, BLACK
		);
	}
	{
		static float constexpr ARROW_SIZE = FREE_SPACE - 20.f;
		static auto const arrow = [&] {
			auto image = GenImageColor(ARROW_SIZE, ARROW_SIZE, BLANK);
			ImageDrawTriangle(&image,
				{ 0.f, ARROW_SIZE / 2, },
				{ ARROW_SIZE / 2, 0.f, },
				{ ARROW_SIZE, ARROW_SIZE / 2, },
			BLACK);
			ImageDrawRectangleRec(&image, { 7.5f, ARROW_SIZE / 2, ARROW_SIZE / 2, ARROW_SIZE / 2, }, BLACK);

			auto ret = LoadTextureFromImage(image);
			UnloadImage(image);
			return ret;
		}();

		DrawTextureEx(arrow, { DEFAULT_SCREEN_SIZE / 2 - ARROW_SIZE / 2, 10.f, },               0.f,   1.f, IsKeyDown(KEY_UP)    && !hasLost ? BLACK : Color{.a = 70});
		DrawTextureEx(arrow, { DEFAULT_SCREEN_SIZE / 2 + ARROW_SIZE / 2, DEFAULT_SCREEN_SIZE - 10.f, }, 180.f, 1.f, IsKeyDown(KEY_DOWN)  && !hasLost ? BLACK : Color{.a = 70});
		DrawTextureEx(arrow, { 10.f, DEFAULT_SCREEN_SIZE / 2 + ARROW_SIZE / 2, },               -90.f, 1.f, IsKeyDown(KEY_LEFT)  && !hasLost ? BLACK : Color{.a = 70});
		DrawTextureEx(arrow, { DEFAULT_SCREEN_SIZE - 10.f, DEFAULT_SCREEN_SIZE / 2 - ARROW_SIZE / 2, }, 90.f,  1.f, IsKeyDown(KEY_RIGHT) && !hasLost ? BLACK : Color{.a = 70});
	}
}
	
Tile Snake::getNextTile() const {
	auto ret = tiles.back();
	switch (direction) {
		case Up:    ret[1]--; break;
		case Down:  ret[1]++; break;
		case Left:  ret[0]--; break;
		case Right: ret[0]++; break;
	}
	if (ret[0] < 0)          ret[0] += GRID_SIZE;
	if (ret[0] >= GRID_SIZE) ret[0] -= GRID_SIZE;
	if (ret[1] < 0)          ret[1] += GRID_SIZE;
	if (ret[1] >= GRID_SIZE) ret[1] -= GRID_SIZE;

	return ret;	
}
void Snake::step(Grid& grid) {

	tiles.push_back(getNextTile());

	bool pop = true;
	for (auto& apple : apples) {
		if (CheckCollisionRecs(
			rectFromIndices(tiles.back(), grid),
			rectFromIndices(apple, grid))
		) {
			pop = false;
			auto newApple = apple;
			do newApple = { dist(e), dist(e), };
			while (
				std::find(tiles.begin(), tiles.end(), newApple) != tiles.end() ||
				std::find(apples.begin(), apples.end(), newApple) != apples.end()
			);
			apple = newApple;
			score++;
			if (score > s_maxScore) s_maxScore++;
		}
	}
	if (pop) tiles.pop_front();
}
