if(NOT DONT_USE_CACHING_COMPILER)
	message(STATUS "Looking for ccache/sccache")
	find_program(CCACHE_PROGRAM ccache)
	find_program(SCCACHE_PROGRAM sccache)
	if(CCACHE_PROGRAM)
		message(STATUS "Using ccache: ${CCACHE_PROGRAM}")
		set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE_PROGRAM} CACHE FILEPATH "C Compiler Launcher")
		set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE_PROGRAM} CACHE FILEPATH "CXX Compiler Launcher")
	elseif(SCCACHE_PROGRAM)
		message(STATUS "Using sccache: ${SCCACHE_PROGRAM}")
		set(CMAKE_C_COMPILER_LAUNCHER ${SCCACHE_PROGRAM} CACHE FILEPATH "C Compiler Launcher")
		set(CMAKE_CXX_COMPILER_LAUNCHER ${SCCACHE_PROGRAM} CACHE FILEPATH "CXX Compiler Launcher")
	else()
		message(STATUS "Not using ccache/sccache.")
	endif()
else()
	message(STATUS "Not looking for ccache/sccache.")
endif()
