
set(INSTALL_TARGETS ${PROJECT_NAME})
if(BUILD_SHARED_LIBS)
	list(APPEND INSTALL_TARGETS ${RAYLIB_TARGET} ${LCB_TARGET} ${IMGUI_TARGET})
endif()
install(
	TARGETS ${INSTALL_TARGETS}
	RUNTIME DESTINATION bin
	LIBRARY DESTINATION lib/${PROJECT_NAME}
)
install(FILES
	"${PROJECT_SOURCE_DIR}/LICENSE"
	"${PROJECT_SOURCE_DIR}/README.md"
	DESTINATION "share/${PROJECT_NAME}"
)
install(DIRECTORY "${PROJECT_SOURCE_DIR}/resources"
	DESTINATION "share/${PROJECT_NAME}")
set_target_properties(${PROJECT_NAME} PROPERTIES INSTALL_RPATH "${APP_RPATH}")
