name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build-type: [Release, RelWithDebInfo]
        include:
          - os: windows-latest
            name: Windows

          - os: macos-latest
            name: MacOS

          - os: ubuntu-latest
            name: Linux

    name: Build ${{ matrix.name }} - ${{ matrix.build-type }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux dependencies
      if: ${{ matrix.os }} == ubuntu-latest
      run: |
        sudo apt-get install -y libx11-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -G "Ninja"
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }}

    - name: Upload
      uses: actions/upload-artifact@v4 
      with:
        name: ${{ matrix.name }} build - ${{ matrix.build-type }}
        path: ${{ github.workspace }}/bin/*
