name: Build Release

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: windows-latest
            name: Windows

          - os: macos-latest
            name: MacOS

          - os: ubuntu-latest
            name: Linux

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux dependencies
      if: matrix.config.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y libx11-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -G "Ninja"
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Upload
      uses: actions/upload-artifact@v4 
      with:
        name: ${{ matrix.config.name }} build - Release
        path: ${{ github.workspace }}/bin/*
