name: Build

on:
  workflow_dispatch:
  push:
    branches:
        - "**"
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Ninja"
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload
      uses: actions/upload-artifact@v4 
      with:
        name: Build Windows
        path: ${{github.workspace}}/build/*.exe

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Ninja"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # thanks chatgpt
    - name: Find built executable
      id: find-executable
      run: |
        # Look for the most recently modified executable in the build folder
        EXECUTABLE=$(find build -type f -perm +111 -exec file {} \; | grep 'Mach-O 64-bit executable' | cut -d: -f1 | head -n 1)
        echo "Executable found at: $EXECUTABLE"
        echo "executable-path=$EXECUTABLE" >> "$GITHUB_OUTPUT"

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Build Macos
        path: ${{steps.find-executable.outputs.executable-path}}

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Ninja"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Build Linux
        path: ${{github.workspace}}/build/*.out

