name: Continous Integration (build)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]

jobs:
  build-Release:
    strategy:
      fail-fast: false
      matrix:
        config:
        - id: win-MSVC
          name: Windows MSVC
          os: windows-latest
          compiler: cl
          generator: 'Visual Studio 17 2022'
          upload-outputs: true

        - id: win-Ninja
          name: Windows Ninja
          os: windows-latest
          compiler: clang
          generator: Ninja

        - id: win-MinGW
          name: Windows MinGW
          os: windows-latest
          compiler: gcc
          generator: MinGW Makefiles

        - id: mac-Xcode
          name: MacOS Xcode
          os: macos-latest
          compiler: clang
          generator: Xcode

        - id: mac-Ninja
          name: MacOS Ninja
          os: macos-latest
          compiler: clang
          generator: Ninja

        - id: mac-Makefiles
          name: MacOS Makefiles
          os: macos-latest
          compiler: gcc
          generator: Unix Makefiles

        - id: linux-Ninja
          name: Linux Ninja
          os: ubuntu-latest
          compiler: clang
          generator: Ninja

        - id: linux-Makefiles
          name: Linux Makefiles
          os: ubuntu-latest
          compiler: gcc
          generator: Unix Makefiles

    name: Build ${{ matrix.config.name }} Release
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.config.os }}
      compiler: ${{ matrix.config.compiler }}
      generator: ${{ matrix.config.generator }}
      shared-libs: ${{ matrix.config.shared-libs }}
      build-type: ${{ matrix.config.build-type }}

  build-RelWithDebInfo:
    strategy:
      fail-fast: false
      matrix:
        id: [ 'win-MSVC', 'win-LLVM', 'mac', 'linux' ]
        compiler: [ 'clang' ]
        generator: [ 'Ninja' ]
        shared-libs: [ true ]
        build-type: [ 'RelWithDebInfo' ]
        include:
          - id: win-MSVC
            name: Windows MSVC
            os: windows-latest
            compiler: cl
            generator: 'Visual Studio 17 2022'

          - id: win-LLVM
            name: Windows LLVM
            os: windows-latest

          - id: mac
            name: MacOS
            os: macos-latest

          - id: linux
            name: Linux
            os: ubuntu-latest

    name: Build ${{ matrix.name }} RelWithDebInfo
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
      compiler: ${{ matrix.compiler }}
      generator: ${{ matrix.generator }}
      shared-libs: ${{ matrix.shared-libs }}
      build-type: ${{ matrix.build-type }}

  win-msi:
    name: Build Windows installer
    needs: build-Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install WiX toolset
        run: |
          curl.exe -LO https://github.com/wixtoolset/wix/releases/download/v6.0.1/wix-cli-x64.msi
          msiexec /i wix-cli-x64.msi /quiet

      - name: Download zip
        uses: actions/download-artifact@v4
        with:
          name: build-win-msvc
          path: ${{ github.ref_name }}

      - name: Build installer
        id: build
        run: |
          $packageName = "${{ github.ref_name }}"
          $version = "1.0.0"
          powershell -ExecutionPolicy Bypass -File .\.github\scripts\build-msi.ps1 `
            -SourceDir .\$packageName `
            -AppName "$packageName" `
            -Manufacturer "Johnny Cena" `
            -Version "$version" `
            -OutputMsi "$packageName-$version.msi"
          echo "installer-path=$packageName-$version.msi" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Test installer
        id: test
        run: |
          $proc = Start-Process -FilePath msiexec.exe `
            -ArgumentList '/i "${{ steps.build.outputs.installer-path }}" /norestart /quiet' `
            -PassThru
          $proc.WaitForExit(30000)
          dir "C:\Program Files\${{ github.ref_name }}"

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.build.outputs.installer-path }}
          name: Windows installer

  linux-deb:
    name: Build Debian package
    needs: build-Release
    runs-on: ubuntu-latest
    steps:
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-linux-Release
          path: ${{ github.workspace }}

      - name: Build
        id: build
        run: |
          sudo apt-get update && sudo apt-get install -y libopengl0 libglu1-mesa
          PACKAGE_NAME=${{ github.ref_name }}
          chmod +x ./$PACKAGE_NAME
          PACKAGE_VERSION=$(./$PACKAGE_NAME --version --minimal-output)
          PACKAGE_DESCRIPTION="$(./$PACKAGE_NAME --description)"
          PACKAGE_DESCRIPTION_MINIMAL="$(./$PACKAGE_NAME --description --minimal-output)"
          PACKAGE_REPO="$(./$PACKAGE_NAME --repo --minimal-output)"
          PACKAGE_DIR="./$PACKAGE_NAME-$PACKAGE_VERSION"
          mkdir -p "$PACKAGE_DIR"/usr/bin
          mv "./$PACKAGE_NAME" "$PACKAGE_DIR/usr/bin/"
          ln -sf libraylib.so.5.5.0 libraylib.so.550
          ln -sf libraylib.so.5.5.0 libraylib.so
          mkdir -p "$PACKAGE_DIR"/usr/lib/$PACKAGE_NAME
          mv ./*.so* "$PACKAGE_DIR/usr/lib/$PACKAGE_NAME/"

          mkdir -p "$PACKAGE_DIR/usr/share/$PACKAGE_NAME/"
          cp -r ./resources "$PACKAGE_DIR/usr/share/$PACKAGE_NAME/"
          ICON_DIR="usr/share/icons"
          mkdir -p "$PACKAGE_DIR/$ICON_DIR"
          ICON_PATH="$ICON_DIR/$PACKAGE_NAME.png"
          cp ./resources/icon.png "$PACKAGE_DIR/$ICON_PATH"
          rm -rf resources

          mkdir -p "$PACKAGE_DIR/usr/share/applications/"
          cat <<EOF > "$PACKAGE_DIR/usr/share/applications/$PACKAGE_NAME.desktop"
          [Desktop Entry]
          Version=1.0
          Name=$PACKAGE_NAME
          GenericName=$PACKAGE_NAME
          Icon=/$ICON_PATH
          Comment=$PACKAGE_DESCRIPTION_MINIMAL. Source code: $PACKAGE_REPO.
          Exec=/usr/bin/$PACKAGE_NAME
          TryExec=/usr/bin/$PACKAGE_NAME
          Terminal=false
          Type=Application
          Categories=Utility;Game;
          Keywords=Game;$PACKAGE_NAME;Raylib;C;CPP;
          EOF

          mkdir -p $PACKAGE_DIR/DEBIAN
          cat <<EOF > "$PACKAGE_DIR/DEBIAN/control"
          Package: $PACKAGE_NAME
          Version: $PACKAGE_VERSION
          Section: utils
          Depends: libc6, libopengl0, libglx0, libglu1-mesa, libstdc++6, libgcc-s1, libx11-6, libxcb1
          Priority: optional
          Architecture: amd64
          Maintainer: Johnny Cena <iamahuman1395@gmail.com>
          Description: $PACKAGE_DESCRIPTION_MINIMAL
            $PACKAGE_DESCRIPTION
            Source code is in $PACKAGE_REPO.
          EOF

          dpkg-deb --build "$PACKAGE_DIR" "$PACKAGE_DIR".deb

          echo "package-path=$PACKAGE_DIR.deb" >> $GITHUB_OUTPUT
        shell: bash

      - name: Test package
        run: |
          sudo dpkg -i ${{ steps.build.outputs.package-path }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.build.outputs.package-path }}
          name: Debian package

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs: [ linux-deb, win-msi, build-RelWithDebInfo ]
    permissions:
      contents: write

    steps:
      - name: Download build outputs
        uses: actions/download-artifact@v4

      - name: Organize
        id: organize
        run: |
          rm -rf "Debian package" "Windows installer"
          mv build-win-msvc/resources .
          rm -rf */resources

          mkdir Release
          mkdir RelWithDebInfo
          mv build-*-RelWithDebInfo RelWithDebInfo/
          mv build-* Release/

          for config in Release RelWithDebInfo; do

            cd $config
              for toolchain in MSVC Ninja; do
                cd build-win-$toolchain-$config && zip -r ../Windows-$toolchain.zip * && cd ..
              done

              cd build-mac-$config
                ln -sf libraylib-$config.5.5.0.dylib libraylib-$config.550.dylib
                ln -sf libraylib-$config.550.dylib libraylib-$config.dylib
                tar -czvf ../MacOS.tar.gz *
              cd ..
              cd build-linux-$config
                ln -sf libraylib-$config.so.5.5.0 libraylib-$config.so.550
                ln -sf libraylib-$config.so.550 libraylib-$config.so
                tar -czvf ../MacOS.tar.gz *
              cd ..
            cd ..
          done
        shell: bash

      - name: Upload Release zip
        uses: actions/upload-artifact@v4
        with:
          path: |
            Release/*.zip
            Release/*.tar.gz
          name: Release Builds

      - name: Upload RelWithDebInfo zip
        uses: actions/upload-artifact@v4
        with:
          path: |
            RelWithDebInfo/*.zip
            RelWithDebInfo/*.tar.gz
          name: RelWithDebInfo Builds

      - name: Upload resources zip
        uses: actions/upload-artifact@v4
        with:
          path: resources/*
          name: resources

      - name: Delete old artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: build-*

  publish:
    name: Publish
    if: github.ref_name != 'Template' 
    permissions:
      contents: write
    needs: cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows installer
        uses: actions/download-artifact@v4
        with:
          name: Windows installer

      - name: Download Debian package
        uses: actions/download-artifact@v4
        with:
          name: Debian package

      - name: Download zips
        uses: actions/download-artifact@v4
        with:
          name: Release Builds

      - name: Prepare
        run: |
          mv Windows-MSVC.zip Windows.zip
          rm Windows-LLVM.zip
        shell: bash

      - name: Delete tag
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: nightly-${{ github.ref_name }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ github.ref_name }}
          name: Development build for ${{ github.ref_name }}
          body: |
            Build triggered by commit ${{ github.sha }} on branch ${{ github.ref_name }}.
            This is a build of the **latest commit**, it is not guaranteed to be stable.
          draft: false
          prerelease: true
          files: |
            *.msi
            *.deb
            *.zip
            *.tar.gz
